version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports: 
      - 27017:27017
    expose:
      - 27017
    networks:
      - test-network

  get-data-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://test:1234@mongo:27017
    depends_on:
      - mongo
    networks:
      - test-network

networks:
   test-network:
     driver: bridge